services:
  db:
    image: postgres:alpine
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - ./env/db.env

  redis:
    image: redis:alpine
    restart: always

  app:
    image: nextcloud:apache
    restart: always
    ports:
      - 127.0.0.1:8001:80
    volumes:
      - nextcloud:/var/www/html
    environment:
      - POSTGRES_HOST=db
      - REDIS_HOST=redis
      - NEXTCLOUD_TRUSTED_DOMAINS=cloud.minglab.top
      - PHP_MEMORY_LIMIT=512M
      - PHP_UPLOAD_LIMIT=1G
      - APACHE_DISABLE_REWRITE_IP=1
      - TRUSTED_PROXIES=localhost
      - OVERWRITEPROTOCOL=https
    env_file:
      - ./env/db.env
      - ./env/nc.env
    depends_on:
      - db
      - redis

  cron:
    image: nextcloud:apache
    restart: always
    volumes:
      - nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

volumes:
  db:
  nextcloud:
