services:
  db:
    image: postgres:alpine
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - ./env/db.env

  nc:
    image: nextcloud:apache
    restart: always
    volumes:
      - nc_data:/var/www/html
    environment:
      - POSTGRES_HOST=db
      - NEXTCLOUD_ADMIN_PASSWORD_FILE=/run/secrets/nextcloud_admin_password
      - NEXTCLOUD_ADMIN_USER_FILE=/run/secrets/nextcloud_admin_user
      - NEXTCLOUD_TRUSTED_DOMAINS=cloud.minglab.top
      - PHP_MEMORY_LIMIT=512M
      - PHP_UPLOAD_LIMIT=512M
      - OVERWRITEHOST=cloud.minglab.top
      - OVERWRITEPROTOCOL=https
    env_file:
      - ./env/db.env
    depends_on:
      - db
    secrets:
      - nextcloud_admin_password
      - nextcloud_admin_user
    ports:
      - 127.0.0.1:8001:80

volumes:
  db_data:
  nc_data:


secrets:
  nextcloud_admin_password:
    file: ./env/nextcloud_admin_password.txt
  nextcloud_admin_user:
    file: ./env/nextcloud_admin_user.txt
