services:
  db:
    image: postgres:alpine
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - ./env/db.env

  redis:
    image: redis:alpine
    restart: always

  app:
    image: nextcloud:apache
    restart: always
    ports:
      - 127.0.0.1:8001:80
    volumes:
      - nextcloud:/var/www/html
    environment:
      - POSTGRES_HOST=db
      - REDIS_HOST=redis
      - NEXTCLOUD_ADMIN_PASSWORD_FILE=/run/secrets/nextcloud_admin_password
      - NEXTCLOUD_ADMIN_USER_FILE=/run/secrets/nextcloud_admin_user
      - NEXTCLOUD_TRUSTED_DOMAINS=cloud.minglab.top
      - PHP_MEMORY_LIMIT=512M
      - PHP_UPLOAD_LIMIT=512M
      - OVERWRITEHOST=cloud.minglab.top
      - OVERWRITEPROTOCOL=https
    env_file:
      - ./env/db.env
    depends_on:
      - db
      - redis
    secrets:
      - nextcloud_admin_password
      - nextcloud_admin_user

  cron:
    image: nextcloud:apache
    restart: always
    volumes:
      - nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

volumes:
  db:
  nextcloud:


secrets:
  nextcloud_admin_password:
    file: ./env/nextcloud_admin_password.txt
  nextcloud_admin_user:
    file: ./env/nextcloud_admin_user.txt
